name: NNAudioSite
options:
  bundleIdPrefix: io.nnaud
  deploymentTarget:
    iOS: 14.0
targets:
  NNAudioSite:
    type: application
    platform: iOS
    sources:
      - path: NNAudioSite
    settings:
      base:
        INFOPLIST_FILE: NNAudioSite/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.nnaud
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: H9K2MR7HPY
    info:
      path: NNAudioSite/Info.plist
      properties:
        CFBundleDisplayName: NNAudio Site
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
